### PR TITLE
Migrate documentation to ember-cli-addon-docs

### LINKED ISSUE #728: Can't find get started guide
I can't find any guide / get start guide on how to use this addon.

### PR DESCRIPTION
**Pull request by hakilebara**
Preview: http://ember-intl-addon-docs.surge.sh/

- install `ember-cli-addon-docs`
- create a quickstart guide
- add live demos of template helpers with dynamic locale switching
- migrate content from `docs/` folder
- migrate code examples from the existing dummy app
- update code example to a more recent Ember syntax 

Overall, I tried to give more structure to the documentation. I am looking forward to hearing your feedback. 

There is still a lot of work to be done. I hope this is useful.

Once this is OK to go, I will need help from a maintainer to deploy the docs to github pages and to setup automatic deploys with Travis.
Fixes #728

### CODE REVIEW

**Comment by jasonmit** [comment]
> Once this is OK to go, I will need help from a maintainer to deploy the docs to github pages and to setup automatic deploys with Travis.

Happy to help with deploying to github pages, let me know what you need from me :)

**Comment by hakilebara** [comment]
> My only comment right now is, can we remove the -private modules from appearing under the Modules section?

Done: https://ember-intl-addon-docs.surge.sh/

I have left `{{-format-base}}`, I don't know if this helper is private or not. Btw in the future, I think all helpers should appear in the API reference section.

**Comment by buschtoens** [comment]
I think this is looking amazing already. Thanks a lot @hakilebara 👏 

Automatic deploys would be set up via [`ember-cli-github-pages`](https://github.com/poetic/ember-cli-github-pages) and a GitHub token on Travis CI.

**Comment by hakilebara** [comment]
@jasonmit shall we merge this?
@buschtoens can you please handle the [travis-ci part](https://ember-learn.github.io/ember-cli-addon-docs/docs/deploying)?

**Comment by jasonmit** [comment]
@buschtoens if you've already done it in the past, I'd really appreciate it :)

**Comment by buschtoens** [comment]
Thanks again @hakilebara 😍
I'll make sure to set up auto-deploy tomorrow!

**Comment by dcyriller** [comment]
> Things still left:
> * figure out how to default the /versions - https://ember-intl.github.io/ember-intl does not work 
>   * I suspect this will resolve itself once we auto publish on deploy

It should resolve itself on the next ember-intl release (when a new tag will be pushed, it will trigger a built distinct from master's).

**Pull request merged**
