### PR TITLE
Make this addon work with CSP

### PR DESCRIPTION
**Pull request by sandstrom**
See https://github.com/ef4/ember-auto-import/issues/275 for more details

### CODE REVIEW

**Comment by jasonmit** [comment]
I believe that webpack config is global in it's all merged together - so this setting can creep into other addon/app builds.  I'm going to wait for @ef4 to respond before merging.

Which libs bundled via webpack are creating the issue?

**Comment by ef4** [comment]
Yes, this setting doesn't belong in addons.

Apps are allowed to control it directly themselves, and this works even if the app doesn't directly depend on ember-auto-import. Apps can say:

```js
let app = new EmberApp(defaults, {
  autoImport: {
    forbidEval: true
  } 
});
```

And that will control ember-auto-import within all their addons.

**Comment by sandstrom** [comment]
@ef4 Isn't it a problem that if an addon we are using switch to ember-auto-import it will break our app?

I've opened an issue in your repo as well, let's continue the discussion there:
https://github.com/ef4/ember-auto-import/issues/275

**Comment by jasonmit** [comment]
@sandstrom I would be fine with a build time warning if we can some how detect if CSP is enabled and !forbidEval.

**Pull request closed without merging**
