### PR TITLE
[WIP] Use `ember-cli-addon-docs` for the dummy app

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @jasonmit

### CODE REVIEW

**Comment by jasonmit** [comment]
Nice!  Thanks for kicking this off.  Let me know where and how you want my involvement, happy to commit time to get this over the finish line.

**Comment by Turbo87** [comment]
@jasonmit I'm busy at the CLI F2F today unfortunately. I think @pzuraq wanted to dig in a little and see how to best structure the API doc comments.

**Comment by pzuraq** [comment]
This should be fixed by https://github.com/ember-learn/ember-cli-addon-docs/pull/139, we're no longer doing anything custom beyond navigation for helpers

**Comment by pzuraq** [comment]
The latest version of ec-addon-docs contains the fix for helpers, let me know if it works for y'all!

**Comment by jasonmit** [comment]
Closing since it's stale.  Let me know what I can do to help move it forward.

**Pull request closed without merging**
