### PR TITLE
fix: updated to reflect current Ember standards

### PR DESCRIPTION
**Pull request by francispeixoto**

### CODE REVIEW

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by longlho** [comment]
hmm looks like build is failing

**Comment by francispeixoto** [comment]
@longlho looks like a known bug with eslint-plugin-ember that was fixed a while ago in their 8.10.1.

bug report: https://github.com/ember-cli/eslint-plugin-ember/issues/905
pull request: https://github.com/ember-cli/eslint-plugin-ember/pull/906
release: https://github.com/ember-cli/eslint-plugin-ember/releases/tag/v8.10.1

for reference, ember-intl is tagging 10.2.0 in master.

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
