### PR TITLE
Initial support for module unification

### LINKED ISSUE #534: Support for apps using module unification resolver
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

[Module Unification RFC](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md)

Where full support may be premature, it would be nice to have at least the basic functionality. Right now addon crashes due to custom `config:*` registrations.

### PR DESCRIPTION
**Pull request by jasonmit**
Fixes #534

TODO:
* [ ] fix tests
* [ ] filter `src` out of the app tree if `EMBER_RESOLVER_MODULE_UNIFICATION` is falsey
* [ ] verify no APIs were broken

### CODE REVIEW

**Comment by tchak** [comment]
I can report that it works on https://github.com/emberjs-paris/website. Thanks!

**Comment by jasonmit** [comment]
Closing for now since there are a bit of conflicts and module unification still needs work before I'm willing to officially support.

**Comment by NullVoxPopuli** [comment]
update:

instead of changing node_modules...

`src/init/initializers/initl-hacks.ts`:
```ts
import Application from '@ember/application';
import IntlService from 'ember-intl/services/intl';

export function initialize(application: Application): void {
  IntlService.reopen({
    lookup(key: string, localeName: string, options: any = {}) {
     const localeNames = this.localeWithDefault(localeName);
     const translation = this._adapter.lookup(localeNames, key);

     if (!options.resilient && translation === undefined) {
       const missingMessage = this._owner.resolveRegistration('util:intl/missing-message');

       return missingMessage.call(this, key, [localeNames]);
     }

     return translation;
   },
  });
}

export default {
  initialize
};

```

**Comment by walter** [comment]
Does this work without typescript in the host app?

I'm migrating a small app that already uses `ember-intl` to the "modern ember" stack with the eventual addition of typescript. However, I want to add typescript last after MU and decorators. Was hoping to get things in a working state before jumping to typescript.

**Comment by NullVoxPopuli** [comment]
Oh yeah. Typescript is always optional. It's just some sugar on top of JavaScript

**Comment by walter** [comment]
I was talking specifically about the code you posted in `src/services/intl.ts`. Do you have a non-typescript version or compiled to js version?

**Comment by walter** [comment]
Plus you removed this block:

```TypeScript
// DO NOT DELETE: this is how TypeScript knows how to look up your services.
declare module '@ember/service' {
  interface Registry {
    'intl': EmberClearIntl
  }
};
```

Thanks for verifying what I suspected. It's good to be explicit about these things for those reading in the future.

I'll have a crack at getting it working and report back if there are any other differences.

**Comment by NullVoxPopuli** [comment]
That registry bit isn't even required for typescript. It's just a helper for the non-decorated service-injection.

**Comment by walter** [comment]
Thanks for your help @NullVoxPopuli, got it working with your additions.

**Pull request closed without merging**
