### PR TITLE
Fix deprecations and warnings in tests

### PR DESCRIPTION
**Pull request by kturney**

### CODE REVIEW

**Comment by jasonmit** [comment]
Still unclear why travis suddenly stopped working.  Will continue to investigate.

**Comment by kturney** [comment]
I guess we could try to move to GitHub actions. I feel like I've been seeing several ember projects transition from Travis to GitHub.

**Comment by jasonmit** [comment]
Moving from travis-ci.org to .com resolved it.  Still open to moving off travis ci.

**Comment by kturney** [comment]
https://github.com/emberjs/data/blob/master/.github/workflows/main.yml

**Pull request merged**
